# -*- coding: utf-8 -*-
"""Chem1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VTDVlu3WYpbpP2xstw1Pfcebs1ARFaj_
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 1.x

!python --version

"""Install rdkit"""

!wget -c https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
!chmod +x Miniconda3-latest-Linux-x86_64.sh
!time bash ./Miniconda3-latest-Linux-x86_64.sh -b -f -p /usr/local
!time conda install -q -y -c conda-forge rdkit

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import sys
import os
sys.path.append('/usr/local/lib/python3.7/site-packages/')

import numpy as np
import pandas as pd

from rdkit import Chem
from rdkit.Chem import DataStructs
from rdkit.Chem import AllChem
from rdkit.Chem import RDConfig
from rdkit import rdBase
from rdkit.Chem.Draw import IPythonConsole

!pip install deepchem

# Train a neural network to predict the solubility of molecules.  First load the data.

import deepchem as dc
tasks, datasets, transformers = dc.molnet.load_delaney(featurizer='GraphConv')
train_dataset, valid_dataset, test_dataset = datasets

# Create and train the model.

model = dc.models.GraphConvModel(n_tasks=1, mode='regression', dropout=0.2)
model.fit(train_dataset, nb_epoch=100)

# Evaluate it.

metric = dc.metrics.Metric(dc.metrics.pearson_r2_score)
print("Training set score")
print(model.evaluate(train_dataset, [metric], transformers))
print("Test set score")
print(model.evaluate(test_dataset, [metric], transformers))

# Use it to predict the solubility of some molecules.

smiles = ['COC(C)(C)CCCC(C)CC=CC(C)=CC(=O)OC(C)C',
          'CCOC(=O)CC',
          'CSc1nc(NC(C)C)nc(NC(C)C)n1',
          'CC(C#C)N(C)C(=O)Nc1ccc(Cl)cc1',
          'Cc1cc2ccccc2cc1C']
from rdkit import Chem
mols = [Chem.MolFromSmiles(s) for s in smiles]
featurizer = dc.feat.ConvMolFeaturizer()
x = featurizer.featurize(mols)
predicted_solubility = model.predict_on_batch(x)
for m,s in zip(smiles, predicted_solubility):
    print()
    print('Molecule:', m)
    print('Predicted solubility:', s)















!pip install nglview

!wget https://raw.githubusercontent.com/deepchem/DeepLearningLifeSciences/master/Chapter05/2d3u.pdb

# import nglview as nv

# view = nv.show_pdbid("2D3U") # load "2D3U" from RCSB PDB and display viewer widget

# view = nv.show_file("2D3U.pdb")

# struct_file = nv.FileStructure("2D3U.pdb")
# view = nv.show_file(struct_file)

# view.representations = [
#     {"type": "cartoon", "params": {
#         "sele": "protein", "color": "residueindex"
#     }},
#     {"type": "ball+stick", "params": {
#         "sele": "ligand"
#     }}
# ]

# view

!echo "Pulling featurized and split ACNN datasets from deepchem"
!wget http://deepchem.io.s3-website-us-west-1.amazonaws.com/featurized_datasets/acnn_core.tar.gz
!echo "Extracting ACNN datasets"
!tar -zxvf acnn_core.tar.gz

# Use a neural network to predict the PDBBind dataset.  First load the data.

import deepchem as dc
pdbbind_tasks, pdbbind_datasets, transformers = dc.molnet.load_pdbbind(featurizer="grid", split="random", subset="core")
train_dataset, valid_dataset, test_dataset = pdbbind_datasets

# Create and train the model.

n_features = train_dataset.X.shape[1]
model = dc.models.MultitaskRegressor(
        n_tasks=len(pdbbind_tasks),
        n_features=n_features,
        layer_sizes=[2000, 1000],
        dropouts=0.5,
        model_dir="pdbbind_nn",
        learning_rate=0.0003)
model.fit(train_dataset, nb_epoch=50)

# Evaluate it.

metric = dc.metrics.Metric(dc.metrics.pearson_r2_score)
train_scores = model.evaluate(train_dataset, [metric], transformers)
test_scores = model.evaluate(test_dataset, [metric], transformers)
print("Train scores")
print(train_scores)
print("Test scores")
print(test_scores)



















