# -*- coding: utf-8 -*-
"""Chem Agent Draw AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hOpgeRAs8U4kqAYHhM0UNqnPcoyIrZfp

Updated ChemAgent
"""

pip install chemdraw

import chemdraw

mol = "O=C(C)Oc1ccccc1C(=O)O"
drawer = chemdraw.Drawer(mol, title=mol)
fig = drawer.draw()
fig.show()

import chemdraw

molecules = [
    "CCCCCCCCCC",
    "CC(CC(CCC)C)CC",
    "CCC1CC1",
    "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O)O)O)O)O",
    "O=C(C)Oc1ccccc1C(=O)O",
    "C1(CCC2)=C3C2=CC4=C5C3=C(CCC5CCC4)C=C1",
    "CC(C)(C)N(C)C(=O)C14C3C2C1C5C2C3C45C(=O)C69C8C7C6C%10C7C8C9%10",
    "CC3C(C(=O)OCC1=CCN2C1C(CC2)OC(=O)C(CC(=O)O3)(C(C)C)O)(C(C)C)O",
    "N#CCC1(CC(O1)C2=CC(=NC2=O)OC)O"
]

drawer = chemdraw.GridDrawer(molecules)
drawer.draw_png("example_2.png")











"""https://chatgpt.com/share/67c68692-7c14-800e-bb22-383d990dc3c7"""

# Install RDKit (Only needed for Google Colab)
!pip install rdkit-pypi

# Import necessary libraries
from rdkit import Chem
from rdkit.Chem import Draw, Descriptors, PandasTools
import pandas as pd

# Define some SMILES strings for demo
smiles_list = [
    "CCO",  # Ethanol
    "CC(=O)O",  # Acetic acid
    "C1=CC=CC=C1",  # Benzene
    "CCN(CC)CC",  # Tetraethylamine
    "CCOC(=O)C1=CC=CC=C1C(=O)OCC"  # Dimethyl terephthalate
]

# Convert SMILES to RDKit Molecule objects
molecules = [Chem.MolFromSmiles(smiles) for smiles in smiles_list]

# Draw the molecules
Draw.MolsToGridImage(molecules, molsPerRow=3, subImgSize=(200, 200))

from rdkit import Chem
from rdkit.Chem import Draw

# Define the SMILES string for pentanoic acid
smiles_pentanoic_acid = "CCCCC(=O)O"

# Convert SMILES to RDKit Molecule object
mol_pentanoic_acid = Chem.MolFromSmiles(smiles_pentanoic_acid)

# Draw the molecule
Draw.MolToImage(mol_pentanoic_acid)

# Import necessary libraries
import matplotlib.pyplot as plt
from rdkit import Chem
from rdkit.Chem import Draw

# Define the SMILES string for butanoic acid
smiles_butanoic_acid = "CCCC(=O)O"

# Convert SMILES to RDKit Molecule object
mol_butanoic_acid = Chem.MolFromSmiles(smiles_butanoic_acid)

# Draw the molecule
img = Draw.MolToImage(mol_butanoic_acid)

# Display the image
plt.imshow(img)
plt.axis("off")
plt.show()

# Import necessary libraries
import matplotlib.pyplot as plt
from rdkit import Chem
from rdkit.Chem import Draw

# Define the SMILES string for propanoic acid (butanoic acid with one less carbon)
smiles_propanoic_acid = "CCC(=O)O"

# Convert SMILES to RDKit Molecule object
mol_propanoic_acid = Chem.MolFromSmiles(smiles_propanoic_acid)

# Draw the molecule
img = Draw.MolToImage(mol_propanoic_acid)

# Display the image
plt.imshow(img)
plt.axis("off")
plt.show()

# Import necessary libraries
from rdkit import Chem
from rdkit.Chem import Draw

# Define the SMILES string for acetic acid
acetic_acid_smiles = "CC(=O)O"

# Convert SMILES to RDKit Molecule object
acetic_acid_molecule = Chem.MolFromSmiles(acetic_acid_smiles)

# Draw the molecule
Draw.MolToImage(acetic_acid_molecule)

# Import necessary libraries
from rdkit import Chem
from rdkit.Chem import Draw

# Define the SMILES string for sodium acetate
sodium_acetate_smiles = "CC(=O)[O-].[Na+]"  # Representing sodium acetate with ionic form

# Convert SMILES to RDKit Molecule object
sodium_acetate_molecule = Chem.MolFromSmiles(sodium_acetate_smiles)

# Draw the molecule
Draw.MolToImage(sodium_acetate_molecule)

pip install py3Dmol

# Import necessary libraries
import py3Dmol

# Define the molecular structure of cyclohexane in boat conformation in XYZ format
boat_cyclohexane_xyz = """12
Cyclohexane Boat Conformation
C  1.214  0.707  0.000
C  0.000  1.414  0.000
C -1.214  0.707  0.000
C -1.214 -0.707  0.000
C  0.000 -1.414  0.000
C  1.214 -0.707  0.000
H  2.157  1.256  0.000
H -2.157  1.256  0.000
H -2.157 -1.256  0.000
H  2.157 -1.256  0.000
H  0.000  2.500  0.000
H  0.000 -2.500  0.000
"""

# Create 3D visualization using py3Dmol
view = py3Dmol.view(width=500, height=500)
view.addModel(boat_cyclohexane_xyz, "xyz")  # Adding XYZ model
view.setStyle({"stick": {"radius": 0.2}})  # Stick representation
view.zoomTo()
view.show()











from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem import PandasTools
# PandasTools ~ rdDepictor
from rdkit import DataStructs
import re

pattern = re.compile("<\?xml.*\?>")


def DrawMol(mol, molSize=(450,150), kekulize=True):
    mc = Chem.MolFromSmiles(mol)
    if kekulize:
        try:
            Chem.Kekulize(mc)
        except:
            mc = Chem.Mol(mol.ToBinary())
    if not mc.GetNumConformers():
        Chem.rdDepictor.Compute2DCoords(mc)

    drawer = rdMolDraw2D.MolDraw2DSVG(*molSize)
    drawer.DrawMolecule(mc)
    drawer.FinishDrawing()
    svg = drawer.GetDrawingText().replace('svg:', '')
    svg = re.sub(pattern, '', svg)
    svg = "<div>" + svg + "</div>"
    return svg

print(DrawMol("CC1=COC2=C1C(=O)C(=O)C3=C2C=CC4=C3CCCC4(C)C"))
#Tanshinone IIA

