# -*- coding: utf-8 -*-
"""Chemical_Dynamical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sqPLnBw45jQjdXh0wcKEliEYkqY5wcog

# Two Component Signaling Pathways and Dynamical Systems

*This tutorial was generated from a Jupyter notebook, which may be downloaded [here](r6_two_component.ipynb).*

The purpose of this tutorial is to investigate in more detail the model of two component signaling pathways that was proposed in class and to illustrate some concepts in analyzing dynamical systems.

We start by considering the model of two component gene expression presented in lecture as depicted in the cartoon below.

<img src="2component.png" width="250px">

Note that the kinase $X$ can also act as a phosphatase in its unphosphorylated form. The phosphorylated form of $Y$ is $Y_p$, which affects downstream cellular behavior. Thus, we will consider $Y_p$ to be the output of this system.

We now start as usual by writing down some ODE's. We will assume standard kinetics for all the reactions in the system (so no Hill functions).

\begin{align}
\dot{X}_p &= v_1(s)\,X - v_3 X_p Y \\[1em]
\dot{Y}_p &= v_3 X_p Y - v_2 X Y_p
\end{align}

However, we have the conservation relations for both $X$ and $Y$.

\begin{align}
X_T &= X + X_p \\[1em]
Y_T &= Y + Y_p
\end{align}

Plugging these in, we get the following ODEs.

\begin{align}
\dot{X}_p &= v_1(s)(X_T - X_p) - v_3 X_p (Y_T - Y_p) \\[1em]
\dot{Y}_p &= v_3 X_p (Y_T - Y_p) - v_2 (X_T - X_p) Y_p
\end{align}

We now have 5 parameters, $v_1(s)$, $v_2$, $v_3$, $X_T$, and $Y_T$.

Let's non-dimensionalize these equations. Start with the following scaling relations, where capital letters have dimensions and lower case letters do not.

\begin{align}
T &= T_0 t \\[1em]
X_p &= X_0 x \\[1em]
Y_p &= Y_0 y
\end{align}

Plugging this in, we get the following equations.

\begin{align}
\frac{X_0}{T_0}\, \frac{dx}{dt} &= v_1(s)(X_T-X_0 x) - v_3 X_0 x (Y_T - Y_0 y) \\[1em]
\frac{Y_0}{T_0}\, \frac{dy}{dt} &= v_3 X_0 x (Y_T-Y_0 y) - v_2 (X_T - X_0 x) Y_0 y
\end{align}

We can simplify things around a bit now.

\begin{align}
\frac{dx}{dt} &= T_0 v_1(s)\left(\frac{X_T}{X_0}-x\right) - T_0 v_3 Y_0 x \left(\frac{Y_T}{Y_0} - y\right) \\[1em]
\frac{dy}{dt} &= T_0 v_3 X_0 x \left(\frac{Y_T}{Y_0}- y\right) - T_0 v_2 X_0 y \left(\frac{X_T}{X_0}- x\right)
\end{align}

Now, let's set $X_0 = X_T$ and $Y_0 = Y_T$ to get the following.

\begin{align}
\frac{dx}{dt} &= T_0 v_1(s)(1-x) - T_0 v_3 Y_T x (1 - y) \\[1em]
\frac{dy}{dt} &= T_0 v_3 X_T x (1-y) - T_0 v_2 X_T y (1 - x)
\end{align}

Now, finally let's set $T_0 = (v_3 X_T)^{-1}$.

\begin{align}
\frac{dx}{dt} &= u_1(s)(1-x) - r x (1 -y) \\[1em]
\frac{dy}{dt} &= x (1-y) - k y (1-x)
\end{align}

Here, we define $u_1(s) = v_1(s) \cdot (v_3 X_T)^{-1}$. Then $r = Y_T / X_T$ and $k = v_2 / v_3$.

Now, we can move onto doing some analysis of these equations.

Before we do anything more, as usual, let's begin by importing the modules we'll need.
"""

# Commented out IPython magic to ensure Python compatibility.
# NumPy and odeint, our workhorses
import numpy as np
import scipy.integrate

# Plotting modules
import matplotlib.pyplot as plt
import seaborn as sns

# This is to enable inline displays for the purposes of the tutorial
# %matplotlib inline
# %config InlineBackend.figure_formats = {'png', 'retina'}

# JB's favorite Seaborn settings for notebooks
rc = {'lines.linewidth': 2,
      'axes.labelsize': 18,
      'axes.titlesize': 18,
      'axes.facecolor': 'DFDFE5'}
sns.set_context('notebook', rc=rc)
sns.set_style('darkgrid', rc=rc)

"""## Analysis of Two Component Signaling

As with any dynamical system, we will start by solving for the steady states. In lecture, we described that at steady state, we would get a value of $Y_p = v_1(s) / v_2$, which provided linear amplification of the signal. However, we did not consider if this steady state was stable, if it was globally attracting, or if there might have other steady states. Here, we will analyze the steady states of the system in more depth.

We start by setting the derivatives equal to zero to solve for the steady states. We will drop the function of $s$ for convenience from now on. Solving these equations yields two possible steady states. The first occurs at $(x,y) = (1,1)$. The second is the steady state shown in class, where

\begin{align}
(x,y) = \left(\frac{ku_1}{rk-u_1+ku_1},\frac{u_1}{rk}\right).
\end{align}

Let's check that $Y_p$ has the correct value here. We know that $Y_p$ has a value given by $v_1/v_2$ from lecture, so let's check if this is correct.

\begin{align}
Y_p &= Y_0 y \\[1em]
    &= Y_0 \frac{u_1}{rk} \\[1em]
    &= Y_T \frac{v_1}{v_3 X_T}  \frac{v_3}{v_2} \frac{X_T}{Y_T}\\[1em]
    &= \frac{v_1}{v_2}
\end{align}

This is good. This means we probably non dimensionalized the equations correctly. The other steady state of $(1,1)$ of course corresponds to the case where $X$ and $Y$ are both fully phosphorylated.

## Stability Analysis for Two Component Signaling

We can now assess the stability of these equilibrium points (steady states). We will start by plotting some nullclines for the system. As we know, we can plot nullclines by setting each derivative term to zero.

\begin{align}
\frac{dx}{dt} &= u_1(1-x) - r x (1 -y) = 0 \\[1em]
\Rightarrow\; y &= 1 - \frac{u_1 (1-x)}{rx}
\end{align}

Similarly, for $dy/dt$,

\begin{align}
\frac{dy}{dt} &= x (1-y) - k y (1-x) = 0\\[1em]
\Rightarrow \; 0 &= x-xy-ky+kxy \\[1em]
\Rightarrow \; x &= -y(-x-k+kx) \\[1em]
\Rightarrow \;y &= \frac{x}{x+k-kx}
\end{align}

We can now plot these null clines and see what happens.
"""

# Set parameter values
u1 = 0.5
r = 1
k = 2

# Buuld curves for plot
x = np.linspace(0.0, 1.5, 1000)
y1 = 1 - u1 * (1 - x) / (r * x)
y2 = x / (x + k - k*x)

# Generate plot
plt.plot(x, y1, x, y2)
plt.xlim((0, 1.5))
plt.ylim((0, 2))
plt.xlabel('$x$', fontsize=24)
plt.ylabel('$y_1,\, y_2$', fontsize=24)
plt.legend(('$y_1$', '$y_2$'), loc="upper left", fontsize=18);

"""The nullclines clearly support our analytical calculation of there being two steady states. However, when we have $u_1 > rk$, one of the steady states occurs at $x,y > 1$. This is unphysical since $x=1$ and $y=1$ correspond to all the protein being phosphorylated, and it is impossible to phosphorylate more protein than you have. Then, we can make sure that our system respects this constraint.

We show that if we start inside the unit box where $0 \leq x,y \leq 1$, then the system stays in the box. To show this, we can simply look at the derivative on the edges of the box.

On the left edge $x=0$, and so $\dot{x} = u_1$ which keeps $x$ from being negative. On the top edge, we have $y=1$, so $\dot{y} = -k(1-x) \leq 0$ so $y$ cannot get bigger than $1$. You can investigate the other steady states as an exercise.

## Phase Plot

We can also make a phase plot for this sytem. A phase plot simply shows the velocity of the system at each point in space. We also overlay the steady states onto the plot. Let's go to work.
"""

#Define derivatives
def xdot(x, y):
    return u1 * (1 - x) - r * x * (1 - y)

def ydot(x, y):
    return x * (1 - y) - k * y * (1 - x)

# Compute moving fixed point.
yeq = u1 / (r * k)
xeq = k * u1 / (r * k - u1 + k * u1)

# Set up x,y space
x = np.linspace(0, max(1, xeq), 100)
y = np.linspace(0, max(1, yeq), 100)
xx, yy = np.meshgrid(x, y)

# Compute derivatives
x_vel = xdot(xx, yy)
y_vel = ydot(xx, yy)

# Compute speed
speed = np.sqrt(x_vel**2 + y_vel**2)

# Make linewidths proportional to speed, with min of 0.5 and max of 5
lw = 0.5 + 4.5 * speed / speed.max()

# Make stream plot and overlay fixed points
plt.streamplot(xx, yy, x_vel, y_vel, linewidth=lw, arrowsize=1.5,
               density=1.25)

plt.plot(xeq, yeq, 'r.', markersize=20)
plt.plot(1, 1, 'r.', markersize=20)
plt.margins(0.02)

print(xeq,yeq)

"""## More General Analysis

As you can see from the phase plot, the equilibrium point corresponding to the linear amplification is globally stable. However, when moving the value $u_1$ to something greater than $rk$, the equilibrium point at $(1,1)$ becomes globally stable. Thus, we have verified the behavior of the two component signaling system as a linear amplifier with saturation.

However, all the techniques we have showed so far require plotting. Thefore, they really only work for two dimensional systems. To assess the stability of equilibrium points in higher dimensions, we need to look at linear stability analysis.

<br />

### Linear Stability Analysis

Given a system described by a set of ODEs where

\begin{align}
\dot{\mathbf x} = f(\mathbf x),
\end{align}

we can compute the Jacobian $Df$ and evaluate it at the equilibrium points. If the eigenvalues of the Jacobian all have a negative real part, then the equilibrium point is locally stable. If any of the eigenvalues have a positive real part, then the equilibrium point is unstable. If some eigenvalues have a zero real part, then it becomes a lot more complicated so don't worry about it.

For two dimensional systems, an equilibrium point is stable if and only if the Jacobian has a negative trace and positive determinant.

For this system, we define the state $\mathbf x$ to be given by

\begin{align}
\mathbf x = \begin{pmatrix}x \\ y\end{pmatrix}.
\end{align}

Then,
\begin{align}
\dot{\mathbf x} &= \begin{pmatrix}\dot{x} \\[1em] \dot{y}\end{pmatrix}
= \begin{pmatrix} u_1(1-x) - r x (1 -y)\\[1em] x (1-y) - k y (1-x)\end{pmatrix},
\end{align}

so

\begin{align}
f(\mathbf x) =
\begin{pmatrix} u_1(1-x) - r x (1 -y)\\[1em]
x (1-y) - k y (1-x)\end{pmatrix}.
\end{align}

Now, we can compute $Df$.

\begin{align}
Df = \begin{pmatrix} -u_1-r(1-y) & rx \\[1em]
                     1-y+ky & -x-k(1-x)
      \end{pmatrix}
\end{align}

We can now evaluate $Df$ at the equilibrium point $(1,1)$. We call this matrix $J$ for the Jacobian.

\begin{align}
J = Df(1,1) = \begin{pmatrix} -u_1 & r \\
                     k & -1
      \end{pmatrix}
\end{align}

Finally, we can evaluate the trace and determinant of $J$.

\begin{align}
\textrm{trace } J &= -u_1 -1 < 0\\[1em]
\det J &= u_1 - rk
\end{align}

The trace is always negative so that's good. The determinant is positive only if $u_1 > rk$. This correponds to a equilibrium point existing at $y > 1$, so this is suggesting that the saturation effect does occur. However, when $u_1 < rk$, this equilibrium point is unstable. This is consistent with the system going to the other steady state that gives the linear amplification behavior.

It is important to note that this analysis is a local analysis only. A linearly stable equilibrium point will attract all trajectories that start somewhere *nearby*, but other trajectories may do other things (cf. bistability). However, in this case the phase plot helps us to conclude that the equilibrium points we are considering are in fact globally stable if they are stable. You may be wondering at this point how one might show global stability for high dimensional systems. This requires a different kind of stability analysis called Lyapunov stability analysis.

As an exercise, you can perform linear stability analysis on the other equilibrium point in this system. You should find that it is linearly stable for $u_1 < rk$ and unstable for $u_1 > rk$.

# Global Stability Analysis

We can also perform global stability analysis for this system. First of all, it is important to note that the system is invariant on the unit square. That is, if $x$ and $y$ are both non-negative and less than or equal to $1$, they will remain that way for all time. This makes sense because it doesn't make sense to be able to have a negative amount of phosphorylated $X$ or $Y$, nor does it make sense to have more phosphorylated $X$ or $Y$ than the total amount of $X$ or $Y$.

To see this, consider $x=0$.

\begin{align}
\frac{dx}{dt} &= u_1(1-x) - r x (1 -y) \\
              &= u_1 > 0
\end{align}

When $x=0$, $\dot x > 0$, so the system can never go into the region of negative $x$.

Then consider $y=0$.

\begin{align}
\frac{dy}{dt} &= x (1-y) - k y (1-x) \\
              &= x \geq 0
\end{align}

So, when $y=0$, $\dot y \geq 0$ and the system can never go into the region of negative $y$.

As an exercise, you can verify for yourself that the system also cannot evolve such that $x,y > 1$.

## Lyapunov Functions

To do global stability analysis, we need to introduce Lyapunov functions. A Lyapunov function is a function $V(x,y)$ such that the following properties are satisfied.

1. $V(x,y) = 0$ at the equilibrium point and $V(x,y) > 0$ everywhere else in the unit square.
2. $\dot V(x) < 0$ everywhere in the unit square except at the equilibrium point.

If we can find such a function $V(x,y)$, then that is sufficient to show that the equilibrium point is globally stable. If you are interested in learning more, try Wikipedia or CDS 140.

Note: In this system, there are two equilibrium points, so the system will end up being globally stable almost everywhere within the unit square, since trajectories that start at $(1,1)$ will not converge to the stable equilibrium point and instead will just sit at $(1,1)$ for all time.

We will try the following Lyapunov function.

\begin{align}
V(x,y) = {\max  \left(\frac{5}{4}\left|x-\frac{2}{5}\right|,\left| y-\frac{1}{4} \right|\right)}
\end{align}

In general, Lyapunov functions are difficult to find and there are not great tools for finding them. The best technique is something called sum of squares programming, which uses convex optimization to search for Lyapunov functions.

We can then plot contours of the Lyapunov function on top of the phase plot from earlier to see what it looks like.
"""

# Plotting the phase plot with Lyapunov contours over it.

# First, redo everything needed to plot the
# original phase plot and eq points as before.

#Define derivatives
def xdot(x, y):
    return u1 * (1 - x) - r * x * (1 - y)

def ydot(x, y):
    return x * (1 - y) - k * y * (1 - x)

# Compute moving fixed point.
yeq = u1 / (r * k)
xeq = k * u1 / (r * k - u1 + k * u1)

# Set up x,y space
x = np.linspace(0, max(1, xeq), 100)
y = np.linspace(0, max(1, yeq), 100)
xx, yy = np.meshgrid(x, y)

# Compute derivatives
x_vel = xdot(xx, yy)
y_vel = ydot(xx, yy)

# Compute speed
speed = np.sqrt(x_vel**2 + y_vel**2)

# Make linewidths proportional to speed, with min of 0.5 and max of 5
lw = 0.5 + 4.5 * speed / speed.max()

# Make stream plot and overlay fixed points
plt.streamplot(xx, yy, x_vel, y_vel, linewidth=lw, arrowsize=1.5,
               density=1.25)

plt.plot(xeq, yeq, 'r.', markersize=20)
plt.plot(1, 1, 'r.', markersize=20)
plt.margins(0.02)

# Now plot the contours of the Lyapunov function over the phase plot.
V = np.maximum(1.25*np.abs(xx-.4),np.abs(yy-.25))
plt.contour(xx, yy, V, colors=sns.color_palette('Purples', 10)[2:]);

"""We can see that the phase lines always go inside the contour squares. This means that the system is always evolving towards a lower value of $V$, and eventually it will end up at the point where $V = 0$, which is the globally stable equilibrium point. This picture shows that our choice of $V$ is a good Lyapunov function for this system, but we still cannot mathematically show stability without actually doing the algebra (or at least some of it).

## Computing the Derivative of V

To get the derivative of $V$, we start by noting that the derivative needs to be calculated in a piecewise manner. Letting $a = x - 0.4$ and $b= y - 0.25$, the derivative $\dot V$ can be computed in the following way.

\begin{align}
-\dot{x} \quad & \textrm{when  } 1.25|a| > |b| \textrm{ and } a < 0 \\
\dot{x} \quad & \textrm{when  } 1.25|a| > |b| \textrm{ and } a > 0 \\
-\dot{y} \quad & \textrm{when  } 1.25|a| < |b| \textrm{ and } b < 0 \\
\dot{y} \quad & \textrm{when  } 1.25|a| < |b| \textrm{ and } b > 0 \\
\end{align}

Then, you can verify for yourself that $\dot V < 0$ in all of these cases, which proves that the system is globally stable.

For example, when $a > 0$ and $1.25|a| > |b|$, we have that $\dot V = \dot x$.

Then,

\begin{align}
\dot V = \dot x &= \frac{1}{2}(1-x)-x(1-y) = -\frac{5}{4}a+\frac{2}{5}b + ab \\
                &< -|b| + \frac{2}{5} b + ab \\
                &\leq -|b| + b \leq 0.
\end{align}

The rest of the cases are left as an exercise.

## Bifurcation Diagrams

Finally, you guys should be familiar with a bifurcation diagram, which is just a plot of the equilibrium points of a system and the way the vary with a certain parameter. Here, the varying parameter is $u_1$. Dotted lines corresponds to unstable equilibria and solid lines are stable equilibria.
"""

# Build arrays for plotting up to bifurcation point
u1 = np.linspace(0, r * k, 100)
y1 = u1 / (r * k)

# Plot up to bifurcation
plt.plot(u1, np.ones_like(u1), 'k--')
plt.plot(u1, y1, 'k-')

# Build arrays for plotting after bifurcation point
u1 = np.linspace(r * k, 2 * r * k, 100)
y1 = u1 / (r * k)

# Finish plot
plt.plot(u1, np.ones_like(u1),'k-')
plt.plot(u1, y1, 'k--')
plt.xlabel('$u_1$', fontsize=24)
plt.ylabel('$y_\mathrm{ss}$', fontsize=24);

"""# Dynamical Systems with Periodic Solutions

Consider the activator-repressor dynamical system given by

\begin{align}
\dot{x} &= \frac{2}{1+y^2} - x \\
\dot{y} &= \frac{2x}{1+x} - y.
\end{align}

Then, the unique equilibrium point is $x_{ss} = y_{ss} = 1$.

We can then verify that the system is stable at that equilibrium point by computing the Jacobian at the equilibrium point, which gives us the following.

\begin{equation}
J = \begin{bmatrix}-1 &  (-) \\ (+)  & -1 \end{bmatrix}
\end{equation}

We don't care about the off-diagonal entries as their sign alone is enough to determine that $\textrm{trace} J < 0$ and $\det J > 0$, which means the equilibrium point is stable. We might then again want to consider whether the equilibrium point is globally stable or if a limit cycle exists.

## Bendixson's Negative Criterion

If a given planar system

\begin{align}
\dot x &= f(x,y) \\
\dot y &= g(x,y)
\end{align}

is such that $\frac{\partial f}{\partial x}+\frac{\partial g}{\partial y}$ never changes sign other than on a set of measure zero, then the system cannot have a periodic solution.

In this system, $\frac{\partial f}{\partial x}+\frac{\partial g}{\partial y}=-1-1= -2$, so we cannot have any periodic solutions. We next consider the following.

## Poincare-Bendixson Theorem

If a given planar system

\begin{align}
\dot x &= f(x,y) \\
\dot y &= g(x,y)
\end{align}

is invariant in a finite region of the plane, then all trajectories go to either a periodic orbit or a stable equilibrium point.

Note: There is some other stuff that is mathematically possible, but it requires you to have a saddle point which does not occur here.


Our system is invariant to a subset of the positive quadrant because when $x$ and $y$ are large enough, the degradation terms will always push us back towards lower $x$ and $y$. Then, we can apply the theorem. Since we just showed that there are no possible periodic orbits, we must converge to a stable equilibrium point. Since there is only one possible equilibrium point, the equilibrium point above that we did linear stability analysis for is actually also globally stable!

This is another roundabout way of getting global stability without doing Lyapunov functions.
"""