# -*- coding: utf-8 -*-
"""PubChem_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9HXY3Fhv6cdNsta2soupHbRQAq5H19a
"""

!pip install pubchempy

import pubchempy as pcp

c = pcp.Compound.from_cid(5090)

print(c.molecular_formula)

print(c.isomeric_smiles)

c

c.to_dict(properties=['atoms', 'bonds', 'inchi'])





!pip install pubchemprops

from pubchemprops.pubchemprops import *

p1 = get_first_layer_props('acetone', ['MolecularWeight', 'IUPACName', 'CanonicalSMILES', 'InChI'])

p1



lysine_props = get_second_layer_props('L-lysine', ['IUPAC Name', 'Canonical SMILES', 'Boiling Point', 'Vapor Pressure', 'LogP', 'Density', 'Flash Point'])

lysine_props

print(lysine_props)

lysine_VP = get_second_layer_props('L-lysine', ['Vapor Pressure'])

lysine_VP

c = pcp.Compound.from_cid(5090)

c

for i in range(10):
  print(i)

c.iupac_name



props = get_second_layer_props(c.iupac_name, ['IUPAC Name', 'Canonical SMILES', 'Boiling Point', 'Vapor Pressure', 'LogP'])

props

lysine_props['Vapor Pressure'][0]['StringValue']





lysine_props['Vapor Pressure'][0]['StringValue']

p1 = get_first_layer_props(c.iupac_name, ['CanonicalSMILES'])

p1['CanonicalSMILES']

for i in range(1,100):
#   print(i)
  try:
    c = pcp.Compound.from_cid(i)
    p1 = get_first_layer_props(c.iupac_name, ['CanonicalSMILES'])
    s = p1['CanonicalSMILES']
    p2 = get_second_layer_props(c.iupac_name, ['IUPAC Name', 'Canonical SMILES', 'Boiling Point', 'Vapor Pressure', 'LogP'])
    v = p2['Vapor Pressure'][0]['StringValue']
    print(s,v)

  except:
    pass
#     print('skip')

for i in range(1,100):
#   print(i)
  try:
    c = pcp.Compound.from_cid(i)
    p1 = get_first_layer_props(c.iupac_name, ['CanonicalSMILES'])
    s = p1['CanonicalSMILES']
    p2 = get_second_layer_props(c.iupac_name, ['IUPAC Name', 'Canonical SMILES', 'Boiling Point', 'Vapor Pressure', 'LogP'])
    v = p2['Boiling Point'][0]['StringValue']
    print(s,v)

  except:
    pass
#     print('skip')

for i in range(1,100):
#   print(i)
  try:
    c = pcp.Compound.from_cid(i)
    p1 = get_first_layer_props(c.iupac_name, ['CanonicalSMILES'])
    s = p1['CanonicalSMILES']
    p2 = get_second_layer_props(c.iupac_name, ['IUPAC Name', 'Canonical SMILES', 'Boiling Point', 'Vapor Pressure', 'LogP'])
    v = p2['LogP'][0]['StringValue']
    print(s,v)
    print(i)
  except:
    pass
#     print('skip')

# Boiling Point, Melting Point, Flash Point, Solubility, Density, Vapor Density, Vapor Pressure, LogP, Stability, Auto-Ignition, Viscosity, Heat of Combustion, Heat of Vaporization, Surface Tension, Ionization Potential, Dissociation Constants

for i in range(1,100):
#   print(i)
  try:
    c = pcp.Compound.from_cid(i)
    p1 = get_first_layer_props(c.iupac_name, ['CanonicalSMILES'])
    s = p1['CanonicalSMILES']
    p2 = get_second_layer_props(c.iupac_name, ['IUPAC Name', 'Canonical SMILES', 'Boiling Point', 'Melting Point', 'Flash Point', 'Solubility', 'Density', 'Vapor Density', 'Vapor Pressure', 'LogP', 'Stability', 'Auto-Ignition', 'Viscosity', 'Heat of Combustion', 'Heat of Vaporization', 'Surface Tension', 'Ionization Potential', 'Dissociation Constants'])
    v = p2['LogP'][0]['StringValue']
    print(s,v)
    print(i)
  except:
    pass
#     print('skip')

for i in range(1,1000):
#   print(i)
  try:
    c = pcp.Compound.from_cid(i)
    p1 = get_first_layer_props(c.iupac_name, ['CanonicalSMILES'])
    s = p1['CanonicalSMILES']
    p2 = get_second_layer_props(c.iupac_name, ['IUPAC Name', 'Canonical SMILES', 'Boiling Point', 'Melting Point', 'Flash Point', 'Solubility', 'Density', 'Vapor Density', 'Vapor Pressure', 'LogP', 'Stability', 'Auto-Ignition', 'Viscosity', 'Heat of Combustion', 'Heat of Vaporization', 'Surface Tension', 'Ionization Potential', 'Dissociation Constants'])
    v = p2['LogP'][0]['StringValue']
    print(s,v)
    print(i)
  except:
    pass
#     print('skip')

